//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbcar.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSatislar
    {
        public int SatisId { get; set; }

        [Required(ErrorMessage ="Ürün ID Boþ Býrakýlamaz !")]
        public Nullable<int> Urun { get; set; }

        [Required(ErrorMessage ="Müþteri ID Boþ Býrakýlamaz !")]
        public Nullable<int> Musteri { get; set; }

        [Required(ErrorMessage ="Adet Kýsmý Boþ Býrakýlamaz !")]
        public Nullable<byte> Adet { get; set; }

        [Required(ErrorMessage ="Fiyat Kýsmý Boþ Býrakýlamaz !")]
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual TblMusteriler TblMusteriler { get; set; }
        public virtual TblUrun TblUrun { get; set; }
    }
}
