//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbcar.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUrun()
        {
            this.TblSatislar = new HashSet<TblSatislar>();
        }
    
        public int UrunId { get; set; }

        [Required(ErrorMessage ="Ürün Adý Boþ Býrakýlamaz !")]
        public string UrunAd { get; set; }

        [Required(ErrorMessage ="Ürün Kategorisi Boþ Býrakýlamaz !")]
        public Nullable<short> UrunKategori { get; set; }
        
        [Required(ErrorMessage ="Fiyat Boþ Býrakýlamaz !")]
        public Nullable<decimal> Fiyat { get; set; }

        [Required(ErrorMessage ="Stok Boþ Býrakýlamaz !")]
        public Nullable<byte> Stok { get; set; }
    
        public virtual TblKategoriler TblKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatislar> TblSatislar { get; set; }
    }
}
